# Generated by Django 4.0.5 on 2022-06-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0003_alter_hotel_hotel_main_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.DecimalField(decimal_places=0, max_digits=10)),
                ('ucode', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
    ]
