# Generated by Django 4.0.5 on 2022-06-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0004_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
        migrations.RemoveField(
            model_name='register',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='register',
            name='ucode',
        ),
    ]
