# Generated by Django 4.0.5 on 2022-06-13 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0006_register_email_register_phone_register_ucode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('imageid', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=20)),
                ('coordinate1', models.CharField(max_length=100)),
                ('coordinate2', models.CharField(max_length=100)),
                ('referencesize', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
