# Generated by Django 4.0.5 on 2022-06-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0007_upload_delete_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='brand',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='upload',
            name='coordinate1',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='upload',
            name='coordinate2',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='upload',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='upload',
            name='imageid',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='upload',
            name='referencesize',
            field=models.CharField(default='', max_length=100),
        ),
    ]
