# Generated by Django 4.0.5 on 2022-06-13 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0008_alter_upload_brand_alter_upload_coordinate1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('hotel_Main_Img', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
    ]
