# Generated by Django 4.0.5 on 2022-06-13 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0010_rename_hotel_main_img_hotel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='brand',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hotel',
            name='coordinate1',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hotel',
            name='coordinate2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hotel',
            name='referenceobjectsize',
            field=models.CharField(default='', max_length=50),
        ),
    ]
