# Generated by Django 4.0.5 on 2022-06-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0012_rename_image_hotel_hotel_main_img_remove_hotel_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='brand',
            field=models.CharField(default='shree cement', max_length=200),
        ),
        migrations.AddField(
            model_name='hotel',
            name='corrdinate1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hotel',
            name='corrdinate2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.CharField(default='', max_length=200),
        ),
    ]
