# Generated by Django 4.0.5 on 2022-06-14 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0013_hotel_brand_hotel_corrdinate1_hotel_corrdinate2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='corrdinate1',
            new_name='coordinate1',
        ),
        migrations.RenameField(
            model_name='hotel',
            old_name='corrdinate2',
            new_name='coordinate2',
        ),
    ]
