# Generated by Django 4.0.5 on 2022-06-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0014_rename_corrdinate1_hotel_coordinate1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='is_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='ref_object_size_height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='hotel',
            name='ref_object_size_width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
