# Generated by Django 4.0.5 on 2022-06-14 06:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0016_remove_tutorial_published_remove_tutorial_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='createddate',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='lastdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='register',
            name='ucode',
            field=models.CharField(max_length=10),
        ),
    ]
