# Generated by Django 4.0.5 on 2022-06-14 07:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0017_register_createddate_register_lastdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='createtime',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='lasttime',
            field=models.TimeField(auto_now=True),
        ),
    ]
