# Generated by Django 4.0.5 on 2022-06-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0020_register_createtime_register_lasttime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='category',
            field=models.CharField(choices=[('1', 'Vendor Staff'), ('2', 'Worker'), ('3', 'Employee'), ('4', 'Admin')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='register',
            name='region',
            field=models.CharField(choices=[('1', 'Andhra Pradesh'), ('2', 'Arunachal Pradesh'), ('3', 'Assam'), ('4', 'Bihar'), ('5', 'Chandigarh'), ('6', 'Chhattisgarh'), ('7', 'Dadra and Nagar Haveli'), ('8', 'Daman and Diu'), ('9', 'Delhi'), ('10', 'Goa'), ('11', 'Gujarat'), ('12', 'Haryana'), ('13', 'Himachal Pradesh'), ('14', 'Jammu and Kashmir'), ('15', 'Jharkhand'), ('16', 'Karnataka'), ('17', 'Kerala'), ('18', 'Lakshadweep'), ('19', 'Madhya Pradesh'), ('20', 'Maharashtra'), ('21', 'Manipur'), ('22', 'Meghalaya'), ('23', 'Mizoram'), ('24', 'Nagaland'), ('25', 'Orissa'), ('26', 'Pondicherry'), ('27', 'Punjab'), ('28', 'Rajasthan'), ('29', 'Sikkim'), ('30', 'Tamil Nadu'), ('31', 'Tripura'), ('32', 'Uttaranchal'), ('33', 'Uttar Pradesh'), ('34', 'West Bengal')], default='1', max_length=50),
        ),
    ]
