# Generated by Django 4.0.5 on 2022-06-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0021_register_category_register_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='fullname',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
    ]
