# Generated by Django 4.0.5 on 2022-06-14 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0024_alter_register_category_alter_register_region'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Upload',
        ),
    ]
