# Generated by Django 4.0.5 on 2022-06-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0026_register_created_by_register_updated_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='register',
            name='category',
            field=models.CharField(default='Vendor Staff', max_length=20),
        ),
        migrations.AlterField(
            model_name='register',
            name='region',
            field=models.CharField(default='Rajasthan', max_length=50),
        ),
    ]
