# Generated by Django 4.0.5 on 2022-06-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0028_rename_name_tutorial_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tutorial',
            new_name='response',
        ),
    ]
