# Generated by Django 4.0.5 on 2022-06-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0029_rename_tutorial_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='hotel_Main_Img',
            new_name='image',
        ),
    ]
